### ISSUE TITLE
Invalid wait time when trying to acquire a lock that is already held

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/consuldotnet#103]
**Describe the bug**

When trying to acquire a lock that is already held, we can sometimes get `BadRequest: Invalid wait time` from the Consul agent.

This has happened at least once when running the `Lock_OneShot` test. Here is an example stack trace:

```
2021-07-05T08:40:47.5355523Z ##[error]Consul.Test.LockTest.Lock_OneShot: Assert.Throws() Failure
2021-07-05T08:40:47.5408798Z   Failed Consul.Test.LockTest.Lock_OneShot [1 s]
2021-07-05T08:40:47.5409479Z   Error Message:
2021-07-05T08:40:47.5410692Z    Assert.Throws() Failure
2021-07-05T08:40:47.5411934Z Expected: typeof(Consul.LockMaxAttemptsReachedException)
2021-07-05T08:40:47.5413473Z Actual:   typeof(Consul.ConsulRequestException): Unexpected response, status code BadRequest: Invalid wait time
2021-07-05T08:40:47.5416422Z ---- Consul.ConsulRequestException : Unexpected response, status code BadRequest: Invalid wait time
2021-07-05T08:40:47.5417896Z   Stack Trace:
2021-07-05T08:40:47.5436227Z      at Consul.GetRequest`1.<Execute>d__10.MoveNext()
2021-07-05T08:40:47.5437302Z --- End of stack trace from previous location where exception was thrown ---
2021-07-05T08:40:47.5439095Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-07-05T08:40:47.5442304Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-07-05T08:40:47.5444541Z    at Consul.KV.<Get>d__13.MoveNext()
2021-07-05T08:40:47.5445321Z --- End of stack trace from previous location where exception was thrown ---
2021-07-05T08:40:47.5446967Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-07-05T08:40:47.5450216Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-07-05T08:40:47.5453159Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2021-07-05T08:40:47.5454481Z    at Consul.Lock.<Acquire>d__24.MoveNext()
2021-07-05T08:40:47.5455274Z --- End of stack trace from previous location where exception was thrown ---
2021-07-05T08:40:47.5456849Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-07-05T08:40:47.5458296Z    at Consul.Lock.<Acquire>d__24.MoveNext()
2021-07-05T08:40:47.5459134Z --- End of stack trace from previous location where exception was thrown ---
2021-07-05T08:40:47.5460803Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-07-05T08:40:47.5463999Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-07-05T08:40:47.5466804Z    at Consul.Test.LockTest.<>c__DisplayClass3_0.<<Lock_OneShot>b__0>d.MoveNext() in D:\a\consuldotnet\consuldotnet\Consul.Test\LockTest.cs:line 123
2021-07-05T08:40:47.5468100Z --- End of stack trace from previous location where exception was thrown ---
2021-07-05T08:40:47.5469839Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-07-05T08:40:47.5473044Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-07-05T08:40:47.5475243Z ----- Inner Stack Trace -----
2021-07-05T08:40:47.5475855Z    at Consul.GetRequest`1.<Execute>d__10.MoveNext()
2021-07-05T08:40:47.5476695Z --- End of stack trace from previous location where exception was thrown ---
2021-07-05T08:40:47.5478379Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-07-05T08:40:47.5481617Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-07-05T08:40:47.5483825Z    at Consul.KV.<Get>d__13.MoveNext()
2021-07-05T08:40:47.5484606Z --- End of stack trace from previous location where exception was thrown ---
2021-07-05T08:40:47.5486514Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-07-05T08:40:47.5489911Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-07-05T08:40:47.5492919Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2021-07-05T08:40:47.5494263Z    at Consul.Lock.<Acquire>d__24.MoveNext()
2021-07-05T08:40:47.5495079Z --- End of stack trace from previous location where exception was thrown ---
2021-07-05T08:40:47.5496798Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-07-05T08:40:47.5498141Z    at Consul.Lock.<Acquire>d__24.MoveNext()
2021-07-05T08:40:47.5498924Z --- End of stack trace from previous location where exception was thrown ---
2021-07-05T08:40:47.5501778Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-07-05T08:40:47.5506072Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-07-05T08:40:47.5509579Z    at Consul.Test.LockTest.<>c__DisplayClass3_0.<<Lock_OneShot>b__0>d.MoveNext() in D:\a\consuldotnet\consuldotnet\Consul.Test\LockTest.cs:line 123
2021-07-05T08:40:47.5510921Z --- End of stack trace from previous location where exception was thrown ---
2021-07-05T08:40:47.5512793Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-07-05T08:40:47.5516539Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

And here are the relevant lines from the Consul agent logs:

```
2021-07-05T08:40:46.277Z [DEBUG] agent.http: Request finished: method=PUT url=/v1/session/create from=127.0.0.1:50340 latency=0s
2021-07-05T08:40:46.280Z [DEBUG] agent.http: Request finished: method=GET url=/v1/kv/test/lock/oneshot?wait=1s from=127.0.0.1:50340 latency=0s
2021-07-05T08:40:46.281Z [DEBUG] agent.http: Request finished: method=PUT url=/v1/kv/test/lock/oneshot?flags=3304740253564472344&acquire=86221ea7-1a48-d137-de1e-2e523f8b147d from=127.0.0.1:50340 latency=0s
2021-07-05T08:40:46.284Z [DEBUG] agent.http: Request finished: method=GET url=/v1/kv/test/lock/oneshot?consistent from=127.0.0.1:50340 latency=0s
2021-07-05T08:40:46.285Z [DEBUG] agent.http: Request finished: method=PUT url=/v1/session/create from=127.0.0.1:50341 latency=998.9µs
2021-07-05T08:40:46.286Z [DEBUG] agent.http: Request finished: method=GET url=/v1/kv/test/lock/oneshot?wait=1s from=127.0.0.1:50341 latency=0s
2021-07-05T08:40:47.285Z [DEBUG] agent.http: Request finished: method=GET url=/v1/kv/test/lock/oneshot?index=313&wait=999ms from=127.0.0.1:50341 latency=999.433ms
2021-07-05T08:40:47.286Z [DEBUG] agent.http: Request finished: method=GET url=/v1/kv/test/lock/oneshot?index=313&wait=ms from=127.0.0.1:50341 latency=0s
2021-07-05T08:41:16.279Z [DEBUG] agent.http: Request finished: method=GET url=/v1/kv/test/lock/oneshot?consistent&index=313 from=127.0.0.1:50340 latency=29.9922598s
```

The next to last line is indeed specifying an invalid wait time: `wait=ms`.

**Expected behavior**

We should never specify an invalid wait time.

**Comment by mfkl** [comment]
Is there a way to repro this consistently?
