### ISSUE TITLE
CI intermittendly failing tests

### ISSUE THREAD

**Issue by mfkl** [G-Research/consuldotnet#114]
CI sometimes fails the test run, I could never repro locally. Started investigating but there are some tricky timing tests as well as time-based implementation logic in the consul code itself.

```
[xUnit.net 00:00:17.08]       timed out: missing session did not terminate renewal loop
[xUnit.net 00:00:17.08]       Expected: True
[xUnit.net 00:00:17.08]       Actual:   False
[xUnit.net 00:00:17.08]       Stack Trace:
[xUnit.net 00:00:17.10]         SessionTest.cs(170,0): at Consul.Test.SessionTest.<Session_Create_RenewPeriodic_TTLExpire>d__5.MoveNext()
[xUnit.net 00:00:17.10]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:17.10]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:17.10]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:17.10]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:17.10]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:17.10]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:17.10]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:17.11]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:17.11]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Error: Consul.Test.SessionTest.Session_Create_RenewPeriodic_TTLExpire: timed out: missing session did not terminate renewal loop
  Failed Consul.Test.SessionTest.Session_Create_RenewPeriodic_TTLExpire [11 s]
  Error Message:
   timed out: missing session did not terminate renewal loop
```

That's one. Seems to rely on code like this, in Session.cs

```
if (DateTime.Now.Subtract(lastRenewTime) > initialTTL)
{
       throw lastException;
}
```
Also looked into these

```
Consul.Test.PolicyTest.Policy_CreateDelete [FAIL]
[xUnit.net 00:00:01.28]       Consul.ConsulRequestException : Unexpected response, status code InternalServerError: The ACL system is currently in legacy mode.
[xUnit.net 00:00:01.28]       Stack Trace:
[xUnit.net 00:00:01.28]         D:\a\consuldotnet\consuldotnet\Consul\Client_PutRequests.cs(352,0): at Consul.PutRequest`2.Execute(CancellationToken ct)
[xUnit.net 00:00:01.28]         D:\a\consuldotnet\consuldotnet\Consul\Policy.cs(135,0): at Consul.Policy.Create(PolicyEntry policy, WriteOptions writeOptions, CancellationToken ct)
[xUnit.net 00:00:01.28]         D:\a\consuldotnet\consuldotnet\Consul.Test\PolicyTest.cs(39,0): at Consul.Test.PolicyTest.Policy_CreateDelete()
[xUnit.net 00:00:01.28]         --- End of stack trace from previous location where exception was thrown ---
```
```
Error: Consul.Test.EventTest.Event_FireList: Consul.ConsulRequestException : Unexpected response, status code Forbidden: ACL not found
  Failed Consul.Test.EventTest.Event_FireList [3 ms]
  Error Message:
   Consul.ConsulRequestException : Unexpected response, status code Forbidden: ACL not found
  Stack Trace:
     at Consul.GetRequest`1.Execute(CancellationToken ct) in D:\a\consuldotnet\consuldotnet\Consul\Client_GetRequests.cs:line 89
   at Consul.Test.EventTest.Event_FireList() in D:\a\consuldotnet\consuldotnet\Consul.Test\EventTest.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
```
Last one should be fixed by https://github.com/mfkl/consuldotnet/commit/c796d23a09b7af2764fadbcfdd6577d0bbbca014

Googling around leads to insight about [some potential token generation update](https://www.consul.io/docs/security/acl/acl-migrate-tokens#acl-token-migration) needed by new versions of consul, but then I see all the other agents with the same config succeeding and I feel like that's not it and probably also a timing issue.

**Comment by mfkl** [comment]
```
Error: Consul.Test.SemaphoreTest.Semaphore_OneShot: System.InvalidOperationException : Failed to create session
  Failed Consul.Test.SemaphoreTest.Semaphore_OneShot [36 ms]
  Error Message:
   System.InvalidOperationException : Failed to create session
---- Consul.ConsulRequestException : Unexpected response, status code InternalServerError: Missing node registration
  Stack Trace:
     at Consul.Semaphore.Acquire(CancellationToken ct) in D:\a\consuldotnet\consuldotnet\Consul\Semaphore.cs:line 343
   at Consul.Semaphore.Acquire(CancellationToken ct) in D:\a\consuldotnet\consuldotnet\Consul\Semaphore.cs:line 456
   at Consul.Test.SemaphoreTest.Semaphore_OneShot() in D:\a\consuldotnet\consuldotnet\Consul.Test\SemaphoreTest.cs:line 98
```
another one
